name: task_craft
description: -.
version: 1.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  cached_network_image: ^3.2.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_hooks: ^0.20.3
  freezed: ^2.4.1
  freezed_annotation: ^2.4.1
  permission_handler: ^11.3.1
  flutter_localizations:
    sdk: flutter
  get_it: ^7.6.0
  go_router: ^14.2.7
  hive: ^2.2.3
  injectable: ^2.1.2
  intl: ^0.19.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  meta: ^1.9.1
  logger: ^2.0.2+1
  flutter_screenutil: ^5.9.0
  dio: ^5.3.3
  retrofit: ^4.0.2
  envied: ^0.5.4+1
  lottie: ^3.1.2
  google_maps_flutter: ^2.5.3
  vibration: ^2.0.0
  pinput: ^5.0.0
  device_info_plus: ^10.1.2
  syncfusion_flutter_datepicker: ^26.2.10
  easy_date_timeline: ^1.0.3
  badges: ^3.1.2
  scrollable_positioned_list: ^0.3.8
  scroll_to_index: ^3.0.1
  timelines: ^0.1.0
  sliding_up_panel: ^2.0.0+1
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  google_sign_in: ^6.2.1
  firebase_messaging: ^15.0.4
  shimmer: ^3.0.0
  date_picker_timeline: ^1.2.5



dev_dependencies:
  bloc_test: ^9.1.2
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  lint: ^2.0.1
  injectable_generator: ^2.1.6
  very_good_analysis: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0
  json_serializable: ^6.7.1
  flutter_native_splash: ^2.3.1
  flutter_app_name: ^0.1.0
  retrofit_generator: ^8.0.0
  envied_generator: ^0.5.4+1
  isar_generator: ^3.1.0+1
  swagger_parser: ^1.18.1


dependency_overrides:
  xml: ^6.3.0

flutter_app_name:
  name: starter kit flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/fonts/icons/
    - .env
  fonts:
    - family: "CustomIcons"
      fonts:
        - asset: assets/fonts/icons/CustomIcons.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"