swagger_parser:
  schema_url: https://getaway.shafiulislam20.workers.dev/doc

  output_directory: lib/api
  language: dart
  json_serializer: freezed
  default_content_type: "application/json"
  extras_parameter_by_default: false
  root_client: true
  root_client_name: RestClient
  export_file: true
  put_in_folder: false
  put_clients_in_folder: false
  merge_clients: false
  client_postfix: Client
  path_method_name: true
  enums_to_json: true
  enums_parent_prefix: true
  unknown_enum_value: true
  squash_clients: true
  mark_files_as_generated: true
  original_http_response: false
  name: "Todo"
  replacement_rules:
    - pattern: "[0-9]+"
      replacement: "DTO"
  skipped_parameters:
    - 'X-Some-Token'