// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCso6gReooGgfaEhUEYLuJwi7fxs2SJ34A',
    appId: '1:747569887837:web:786d0318b0fcc47ad92bb4',
    messagingSenderId: '747569887837',
    projectId: 'task-craft-e0aed',
    authDomain: 'task-craft-e0aed.firebaseapp.com',
    storageBucket: 'task-craft-e0aed.appspot.com',
    measurementId: 'G-10VX7EBP25',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbGfk5wf3xOHi-ZPyZY7aTtxdMuu5-ZDU',
    appId: '1:747569887837:android:b3d624615f098428d92bb4',
    messagingSenderId: '747569887837',
    projectId: 'task-craft-e0aed',
    storageBucket: 'task-craft-e0aed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjHIABF7gk9hlCXpN-eO10nAB3TQ4-d8Y',
    appId: '1:747569887837:ios:18950613cded3b3cd92bb4',
    messagingSenderId: '747569887837',
    projectId: 'task-craft-e0aed',
    storageBucket: 'task-craft-e0aed.appspot.com',
    iosBundleId: 'info.ishaf.taskcraft',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjHIABF7gk9hlCXpN-eO10nAB3TQ4-d8Y',
    appId: '1:747569887837:ios:8c718879f0077c42d92bb4',
    messagingSenderId: '747569887837',
    projectId: 'task-craft-e0aed',
    storageBucket: 'task-craft-e0aed.appspot.com',
    iosBundleId: 'com.example.sampleProject',
  );
}
