// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuXLSoVQfi5hH-pesWmfF5UtjsXs1gB-E',
    appId: '1:287218143583:web:38408b8a9f7fecfd1126ea',
    messagingSenderId: '287218143583',
    projectId: 'task-craft-dev',
    authDomain: 'task-craft-dev.firebaseapp.com',
    storageBucket: 'task-craft-dev.appspot.com',
    measurementId: 'G-PPEQ5ZZZLK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6itGFxS4E_RSRnJhHyJnFxWpRPaCdWI8',
    appId: '1:287218143583:android:e44a1c3c1f68accc1126ea',
    messagingSenderId: '287218143583',
    projectId: 'task-craft-dev',
    storageBucket: 'task-craft-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkxOyZ_cHrYfN_UuNIH7mKDt_-oV3E_Kw',
    appId: '1:287218143583:ios:45162684eddb6dd61126ea',
    messagingSenderId: '287218143583',
    projectId: 'task-craft-dev',
    storageBucket: 'task-craft-dev.appspot.com',
    iosBundleId: 'info.ishaf.taskcraft.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkxOyZ_cHrYfN_UuNIH7mKDt_-oV3E_Kw',
    appId: '1:287218143583:ios:8d3d0188ee11123d1126ea',
    messagingSenderId: '287218143583',
    projectId: 'task-craft-dev',
    storageBucket: 'task-craft-dev.appspot.com',
    iosBundleId: 'com.example.sampleProject',
  );
}
