/// Flutter icons CustomIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData alipaycircle = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alipaysquare = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ant = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ant_1 = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData app = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData appstore = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrowdowncircle = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrowsalt = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData audio = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData audio_1 = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData audiomuted = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData avatar = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bankcard = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bellmute = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bill = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calculator = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chatadd = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chatcheck = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chatwrong = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checkbox = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checkcircle = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checkcircle_1 = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checkshield = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checkshield_1 = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clockcircle = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clockcircle_1 = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData closecircle = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData closecircle_1 = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData closeshield = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData collectmoney = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData compass = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData content = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coupon = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData downcircle = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_down = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData downland = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edits = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData environment = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edits_1 = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exclamation = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exclamationcircle = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exclamationcircle_1 = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exclamationshield = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exclamationtriangle = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exclamationshield_1 = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eyeinvisible = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_1 = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eyeinvisible_1 = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facerecognition = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filewrong = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fillin = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter_1 = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData firefill = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forbid = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flag = IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gift = IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder = IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData frown_1 = IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData frown = IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData global = IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heartfill = IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData informationcircle = IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData informationcircle_1 = IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData handpaycircle = IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left = IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData like = IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData koubei = IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData histogram = IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData link = IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData koubei_1 = IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location = IconData(0xe852, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_1 = IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_1 = IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData loop = IconData(0xe855, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock = IconData(0xe856, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail_1 = IconData(0xe857, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mailopen = IconData(0xe858, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message = IconData(0xe859, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData key = IconData(0xe85a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message_1 = IconData(0xe85b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minuscircle = IconData(0xe85c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minus = IconData(0xe85d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData movie = IconData(0xe85e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paycircle = IconData(0xe85f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail = IconData(0xe860, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phonebook_1 = IconData(0xe861, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phonebook = IconData(0xe862, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more = IconData(0xe863, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phonefill = IconData(0xe864, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData picture = IconData(0xe865, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pictures = IconData(0xe866, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData picturewrong = IconData(0xe867, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pie = IconData(0xe868, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play = IconData(0xe869, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData questioncircle = IconData(0xe86a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData questioncircle_1 = IconData(0xe86b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData receipt = IconData(0xe86c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData receivepayment = IconData(0xe86d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData redo = IconData(0xe86e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_right = IconData(0xe86f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scancode = IconData(0xe870, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scanning = IconData(0xe871, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scanningface = IconData(0xe872, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe873, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send = IconData(0xe874, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData set_icon = IconData(0xe875, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopbag = IconData(0xe876, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shrink = IconData(0xe877, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sliderthumb = IconData(0xe878, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData smile = IconData(0xe879, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData smile_1 = IconData(0xe87a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sound = IconData(0xe87b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData soundmute = IconData(0xe87c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData soundmute_1 = IconData(0xe87d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star = IconData(0xe87e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData starfill = IconData(0xe87f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stop = IconData(0xe880, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData systemqrcode = IconData(0xe881, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tag = IconData(0xe882, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData team = IconData(0xe883, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData team_1 = IconData(0xe884, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData text = IconData(0xe885, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData textdeletion = IconData(0xe886, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData transportqrcode = IconData(0xe887, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData travel = IconData(0xe888, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData truck = IconData(0xe889, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData undo = IconData(0xe88a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unlock = IconData(0xe88b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unorderedlist = IconData(0xe88c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up = IconData(0xe88d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData upcircle = IconData(0xe88e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData upload = IconData(0xe88f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up_up = IconData(0xe890, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe891, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData useradd = IconData(0xe892, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData usercircle = IconData(0xe893, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData usercontact = IconData(0xe894, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData userset = IconData(0xe895, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video = IconData(0xe897, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData aa = IconData(0xe898, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add = IconData(0xe899, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData addcircle = IconData(0xe89a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData addressbook = IconData(0xe89b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData addsquare = IconData(0xe89c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apple_filled = IconData(0xe89d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apple_outline = IconData(0xe89e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google_outline = IconData(0xe89f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook_outline = IconData(0xe8a0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google_square = IconData(0xe8a1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google_circle = IconData(0xe8a2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook_filled = IconData(0xe8a3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete_outline = IconData(0xe8a5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData copy_tone = IconData(0xe8a6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData copy_filled = IconData(0xe8a7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData copy_outline = IconData(0xe8a8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = IconData(0xe8af, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
